### ISSUE TITLE
Steps to run this model on GAP Hardware ?

### ISSUE THREAD

**Issue by anujdutt9** [xperience-ai/gap_quantization#13]
Hi. 

1. Can you please add in some instructions on how to run this model on GAP Hardware? 
2. Also, did you make use of the NNTools or TF2GAP8 frameworks to convert the PyTorch model and run that on the hardware or are you running the quantized PyTorch model as is?

Thanks.

**Comment by mzemlyanikin** [comment]
Hi,

We used this tool to quantize the model for GAP8. To run it on GAP8 we implemented a model with Autotiler tool and used the quantized weights from this quantization framework.
It was done for face recognition network and we are going to release the code and instructions to reproduce the full pipeline from neural network training to porting it to GAP8.

We didn't use NNTool or TF2GAP8, but we want to try NNTool to convert the model as it should create the Autotiler code automatically.

**Comment by anujdutt9** [comment]
Hi @wonnado Thanks for the update. Is there any timeline for the full pipeline to be released ? Thanks.

**Comment by mzemlyanikin** [comment]
@anujdutt9, I hope we'll release it in a month.

**Comment by mzemlyanikin** [comment]
Hi @anujdutt9,
We have recently released the code for face recognition neural network training, quantization (this repository is used for quantization actually) and porting model to GAP8.
You can find it [here](https://github.com/GreenWaves-Technologies/FaceReID).

**Comment by anujdutt9** [comment]
Hi, @wonnado Thanks a lot for the update. I'll try it out now. Thanks 👍
